
[platformio]
default_envs = esp32-rx, esp32-tx, esp8266-rx, esp8266-tx

[env]
build_flags =
  -std=c++14
  -Wall

[esp32_base]
platform = espressif32
board = lolin32
framework = arduino
lib_deps =
  yoursunny/WifiEspNow @ ^0.0.20230713

[esp8266_base]
platform = espressif8266
board = d1_mini
framework = arduino
lib_deps =
  yoursunny/WifiEspNow @ ^0.0.20230713

[env:esp32-rx]
extends = esp32_base
build_src_filter = +<*> +<../examples/rx/rx.cpp>

[env:esp32-tx]
extends = esp32_base
build_src_filter = +<*> +<../examples/tx/tx.cpp>

[env:esp8266-rx]
extends = esp8266_base
build_src_filter = +<*> +<../examples/rx/rx.cpp>

[env:esp8266-tx]
extends = esp8266_base
build_src_filter = +<*> +<../examples/tx/tx.cpp>

; library builds here with the stub platform; run with `pio test -e native`
[env:native]
platform = native
test_build_src = yes
build_flags =
  ${env.build_flags}
  -g
